# Generated by Django 3.2 on 2023-09-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230913_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariant',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sizevariant',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(upload_to='catgories'),
        ),
    ]
